name = "xgvst-workers"
main = "src/index.ts"
compatibility_date = "2026-02-23"
workers_dev = true

# Non-sensitive runtime vars can be placed in [vars] when needed.
# Secrets must be injected via: wrangler secret put <NAME>

[[kv_namespaces]]
binding = "QUOTE_KV"
id = "e52352ff583f4ebdb6c8256f2a97c931"
preview_id = "a10795c3cd464308883ce1f48ff2281a"

[[d1_databases]]
binding = "QUOTE_DB"
database_name = "xgvst_quote"
database_id = "9db19911-21e7-4245-8c94-6571aa7a35fb"

[[durable_objects.bindings]]
name = "QUOTE_DO"
class_name = "QuoteDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["QuoteDurableObject"]
